version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Berlin"
    labels:
      - "ci"
      - "chore"
    commit-message:
      prefix: "ci"
    groups:
      actions-minor:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Berlin"
    labels:
      - "chore"
    commit-message:
      prefix: "chore"
    groups:
      docker-minor:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Berlin"
    labels:
      - "chore"
    commit-message:
      prefix: "chore"
    groups:
      npm-minor:
        update-types:
          - "minor"
          - "patch"
